
package cxf_server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IHelloServiceService", targetNamespace = "http://cxf_server/", wsdlLocation = "http://127.0.0.1:8181/hihi?wsdl")
public class IHelloServiceService
    extends Service
{

    private final static URL IHELLOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IHELLOSERVICESERVICE_EXCEPTION;
    private final static QName IHELLOSERVICESERVICE_QNAME = new QName("http://cxf_server/", "IHelloServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8181/hihi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IHELLOSERVICESERVICE_WSDL_LOCATION = url;
        IHELLOSERVICESERVICE_EXCEPTION = e;
    }

    public IHelloServiceService() {
        super(__getWsdlLocation(), IHELLOSERVICESERVICE_QNAME);
    }

    public IHelloServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IHELLOSERVICESERVICE_QNAME, features);
    }

    public IHelloServiceService(URL wsdlLocation) {
        super(wsdlLocation, IHELLOSERVICESERVICE_QNAME);
    }

    public IHelloServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IHELLOSERVICESERVICE_QNAME, features);
    }

    public IHelloServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHelloServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "IHelloServicePort")
    public IHelloService getIHelloServicePort() {
        return super.getPort(new QName("http://cxf_server/", "IHelloServicePort"), IHelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "IHelloServicePort")
    public IHelloService getIHelloServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf_server/", "IHelloServicePort"), IHelloService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IHELLOSERVICESERVICE_EXCEPTION!= null) {
            throw IHELLOSERVICESERVICE_EXCEPTION;
        }
        return IHELLOSERVICESERVICE_WSDL_LOCATION;
    }

}
